--CREATE DATABASE db_outbox_pattern_service;

CREATE USER user_migration_outbox_pattern_service WITH CREATEROLE ENCRYPTED PASSWORD 'password_user_migration_outbox_pattern_service';

GRANT CONNECT ON DATABASE db_outbox_pattern_service TO user_migration_outbox_pattern_service;

GRANT ALL PRIVILEGES ON DATABASE db_outbox_pattern_service TO user_migration_outbox_pattern_service;