spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: schema_outbox_pattern_service
  flyway:
    schemas: ${spring.jpa.properties.hibernate.default_schema}
    placeholders:
      springJpaPropertiesHibernateDefaultSchema: ${spring.jpa.properties.hibernate.default_schema}
      springDatasourceUsername: ${spring.datasource.username}
      springDatasourcePassword: ${spring.datasource.password}
  security:
    user:
      name: user
      password: password
